baseURL: "https://juanpacheco.netlify.app/"
languageCode: en-us
title: Juan Pacheco
theme: minimal
disqusShortname: username
googleAnalytics: ''
params:
  accent: red
  author: 
  backgroundColor: white
  description: Personal Blog
  font: Raleway
  githubUsername: 'jalfred714'
  highlight: yes
  highlightLanguages:
    - go
    - haskell
    - kotlin
    - scala
    - swift
  highlightStyle: default
  showBorder: yes
menu:
  icon:
    - name: fas fa-envelope
      url: mailto:juanalfred16@hotmail.com
      weight: 1
    - name: fab fa-github
      url: https://github.com/jalfred714/
      weight: 2
    - name: fab fa-twitter
      url: https://twitter.com/jalfred7/
      weight: 3
    - name: fab fa-linkedin
      url: https://www.linkedin.com/in/juan-pacheco-314263111/
      weight: 4
   
  main:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: /about/
      weight: 2
    - name: Posts
      url: /post/
      weight: 3
    - name: Projects
      url: /project/
      weight: 4
    - name: Articles
      url: /article/
      weight: 5


      